const defineChampion = (id, preferred, flex = [], name = id) => ({
  id,
  name,
  preferred,
  flex,
});

const championList = [
  defineChampion("Alistar", ["support"]),
  defineChampion("Ahri", ["mid"]),
  defineChampion("Akali", ["mid"], ["top"]),
  defineChampion("Ambessa", ["top"]),
  defineChampion("Akshan", ["mid"], ["bot"]),
  defineChampion("Amumu", ["jungle"], ["support"]),
  defineChampion("Anivia", ["mid"], ["support"]),
  defineChampion("Annie", ["mid"], ["support"]),
  defineChampion("Aphelios", ["bot"]),
  defineChampion("Ashe", ["bot"], ["support"]),
  defineChampion("Aurora", ["mid", "top"]),
  defineChampion("AurelionSol", ["mid"], [], "Aurelion Sol"),
  defineChampion("Azir", ["mid"]),
  defineChampion("Bard", ["support"]),
  defineChampion("Belveth", ["jungle"], [], "Bel'Veth"),
  defineChampion("Blitzcrank", ["support"]),
  defineChampion("Braum", ["support"]),
  defineChampion("Briar", ["jungle"]),
  defineChampion("Caitlyn", ["bot"]),
  defineChampion("Camille", ["top"]),
  defineChampion("Chogath", ["top"], [], "Cho'Gath"),
  defineChampion("Corki", ["mid", "bot"]),
  defineChampion("Darius", ["top"]),
  defineChampion("Diana", ["jungle", "mid"]),
  defineChampion("Draven", ["bot"]),
  defineChampion("Ekko", ["jungle", "mid"]),
  defineChampion("Elise", ["jungle"]),
  defineChampion("Ezreal", ["bot"]),
  defineChampion("Fiora", ["top"]),
  defineChampion("Fizz", ["mid"]),
  defineChampion("Galio", ["mid"], ["support"]),
  defineChampion("Gangplank", ["top"]),
  defineChampion("Garen", ["top"]),
  defineChampion("Gnar", ["top"]),
  defineChampion("Gragas", ["jungle", "top"], ["mid", "support"]),
  defineChampion("Graves", ["jungle"], ["bot"]),
  defineChampion("Gwen", ["top"]),
  defineChampion("Hecarim", ["jungle"]),
  defineChampion("Heimerdinger", ["mid", "top"], ["bot", "support"]),
  defineChampion("Illaoi", ["top"]),
  defineChampion("Irelia", ["top", "mid"]),
  defineChampion("Ivern", ["jungle"]),
  defineChampion("Janna", ["support"]),
  defineChampion("JarvanIV", ["jungle"], ["top"], "Jarvan IV"),
  defineChampion("Jayce", ["top", "mid"]),
  defineChampion("Jhin", ["bot"]),
  defineChampion("Jinx", ["bot"]),
  defineChampion("Kalista", ["bot"]),
  defineChampion("Karma", ["support", "mid"]),
  defineChampion("Karthus", ["jungle"], ["mid"]),
  defineChampion("Katarina", ["mid"]),
  defineChampion("Kayle", ["top"], ["mid"]),
  defineChampion("Kaisa", ["bot"], [], "Kai'Sa"),
  defineChampion("Kassadin", ["mid"]),
  defineChampion("Kennen", ["top"]),
  defineChampion("Khazix", ["jungle"], [], "Kha'Zix"),
  defineChampion("Kindred", ["jungle"]),
  defineChampion("Kled", ["top"]),
  defineChampion("KogMaw", ["bot"], [], "Kog'Maw"),
  defineChampion("KSante", ["top"], [], "K'Sante"),
  defineChampion("Leblanc", ["mid"], [], "LeBlanc"),
  defineChampion("LeeSin", ["jungle"], [], "Lee Sin"),
  defineChampion("Leona", ["support"]),
  defineChampion("Lissandra", ["mid"], ["support"]),
  defineChampion("Locke", ["mid"]),
  defineChampion("Lulu", ["support"]),
  defineChampion("Lucian", ["bot"], ["mid"]),
  defineChampion("Lux", ["support", "mid"]),
  defineChampion("Malphite", ["top"], ["mid", "support"]),
  defineChampion("Malzahar", ["mid"]),
  defineChampion("Maokai", ["jungle", "support"], ["top"]),
  defineChampion("Milio", ["support"]),
  defineChampion("MissFortune", ["bot"], [], "Miss Fortune"),
  defineChampion("MonkeyKing", ["jungle", "top"], [], "Wukong"),
  defineChampion("Morgana", ["support"], ["mid", "jungle"]),
  defineChampion("Naafiri", ["mid"], ["jungle"]),
  defineChampion("Nasus", ["top"]),
  defineChampion("Nautilus", ["support"], ["jungle", "mid"]),
  defineChampion("Neeko", ["mid"], ["support", "bot"]),
  defineChampion("Nidalee", ["jungle"]),
  defineChampion("Nilah", ["bot"]),
  defineChampion("Nocturne", ["jungle"]),
  defineChampion("Nunu", ["jungle"], ["mid"]),
  defineChampion("Olaf", ["top", "jungle"]),
  defineChampion("Orianna", ["mid"]),
  defineChampion("Ornn", ["top"], ["support"]),
  defineChampion("Pantheon", ["top", "mid"], ["support"]),
  defineChampion("Poppy", ["jungle", "top"], ["support"]),
  defineChampion("Pyke", ["support"], ["mid"]),
  defineChampion("Qiyana", ["mid"], ["jungle"]),
  defineChampion("Quinn", ["top"], ["bot"]),
  defineChampion("Rammus", ["jungle"]),
  defineChampion("Rakan", ["support"]),
  defineChampion("Rell", ["support"]),
  defineChampion("Renata", ["support"]),
  defineChampion("RekSai", ["jungle"], [], "Rek'Sai"),
  defineChampion("Renekton", ["top"]),
  defineChampion("Rengar", ["jungle"], ["top"]),
  defineChampion("Riven", ["top"]),
  defineChampion("Rumble", ["top"], ["mid"]),
  defineChampion("Samira", ["bot"]),
  defineChampion("Sejuani", ["jungle"], ["top", "support"]),
  defineChampion("Senna", ["support"], ["bot"]),
  defineChampion("Seraphine", ["support"], ["mid", "bot"]),
  defineChampion("Shaco", ["jungle"], ["support"]),
  defineChampion("Shen", ["top"], ["support"]),
  defineChampion("Shyvana", ["jungle"]),
  defineChampion("Singed", ["top"]),
  defineChampion("Sion", ["top"]),
  defineChampion("Sivir", ["bot"]),
  defineChampion("Smolder", ["bot"]),
  defineChampion("Sona", ["support"]),
  defineChampion("Soraka", ["support"]),
  defineChampion("Swain", ["mid", "bot"], ["support"]),
  defineChampion("Sylas", ["mid"]),
  defineChampion("Taliyah", ["mid", "jungle"]),
  defineChampion("Talon", ["mid"], ["jungle"]),
  defineChampion("TahmKench", ["top", "support"], [], "Tahm Kench"),
  defineChampion("Taric", ["support"]),
  defineChampion("Teemo", ["top"], ["support"]),
  defineChampion("Thresh", ["support"], ["bot"]),
  defineChampion("Tristana", ["bot"], ["mid"]),
  defineChampion("Trundle", ["jungle", "top"], ["support"]),
  defineChampion("Tryndamere", ["top"], ["mid"]),
  defineChampion("TwistedFate", ["mid"], [], "Twisted Fate"),
  defineChampion("Twitch", ["bot"], ["jungle"]),
  defineChampion("Udyr", ["jungle", "top"]),
  defineChampion("Urgot", ["top"]),
  defineChampion("Vayne", ["bot"], ["top"]),
  defineChampion("Veigar", ["mid"], ["bot"]),
  defineChampion("Velkoz", ["support", "mid"], [], "Vel'Koz"),
  defineChampion("Vex", ["mid"]),
  defineChampion("Vi", ["jungle"]),
  defineChampion("Viego", ["jungle"]),
  defineChampion("Viktor", ["mid"]),
  defineChampion("Volibear", ["top", "jungle"]),
  defineChampion("Warwick", ["jungle"], ["top"]),
  defineChampion("Xayah", ["bot"]),
  defineChampion("Xerath", ["mid", "support"]),
  defineChampion("XinZhao", ["jungle"], [], "Xin Zhao"),
  defineChampion("Yasuo", ["mid"], ["bot"]),
  defineChampion("Yone", ["mid", "top"]),
  defineChampion("Yorick", ["top"]),
  defineChampion("Zac", ["jungle"], ["top", "support"]),
  defineChampion("Zed", ["mid"]),
  defineChampion("Zeri", ["bot"]),
  defineChampion("Ziggs", ["mid", "bot"]),
  defineChampion("Zilean", ["mid", "support"]),
  defineChampion("Zoe", ["mid"], ["support"]),
  defineChampion("Zyra", ["support"], ["jungle"]),
];

export const champions = new Map(
  championList.map((champion) => [champion.id, champion]),
);

export function getChampion(id) {
  const champion = champions.get(id);
  if (!champion) throw new Error(`Unknown champion: ${id}`);
  return champion;
}

export const pool = (...ids) => ids.map(getChampion);
