import { pool } from "./champions.js";

export const drafts = [
  {
    id: "freljord",
    title: "All Freljord",
    type: "Lore",
    accent: "#8dd8ef",
    description:
      "A frozen-north roster with a durable frontline and heavy crowd control. Layer slows and stuns around Ashe, Anivia, or Lissandra.",
    sample: {
      top: "Ornn",
      jungle: "Sejuani",
      mid: "Anivia",
      bot: "Ashe",
      support: "Braum",
    },
    champions: pool(
      "Anivia",
      "Ashe",
      "Aurora",
      "Braum",
      "Gnar",
      "Gragas",
      "Lissandra",
      "Nunu",
      "Olaf",
      "Ornn",
      "Sejuani",
      "Trundle",
      "Tryndamere",
      "Udyr",
      "Volibear",
    ),
  },
  {
    id: "piltover",
    title: "All Piltover",
    type: "Lore",
    accent: "#e6bd69",
    description:
      "Piltover's inventors and enforcers offer range and pick potential. Isolate targets with Vi or Camille while ranged carries follow safely.",
    sample: {
      top: "Camille",
      jungle: "Vi",
      mid: "Orianna",
      bot: "Caitlyn",
      support: "Seraphine",
    },
    champions: pool(
      "Caitlyn",
      "Camille",
      "Ezreal",
      "Heimerdinger",
      "Jayce",
      "Orianna",
      "Seraphine",
      "Vi",
    ),
  },
  {
    id: "hooks",
    title: "Everybody Hooks",
    type: "Shared mechanic",
    accent: "#ff8159",
    description:
      "Every champion can pull enemies out of position. Land one hook, save the next for their escape, and fight from fog.",
    sample: {
      top: "Darius",
      jungle: "Nautilus",
      mid: "Pyke",
      bot: "Swain",
      support: "Blitzcrank",
    },
    champions: pool(
      "Blitzcrank",
      "Darius",
      "Kled",
      "Nautilus",
      "Pyke",
      "Renata",
      "Swain",
      "Thresh",
      "Urgot",
      "Zac",
    ),
  },
  {
    id: "pets",
    title: "Pets & Pals",
    type: "Shared mechanic",
    accent: "#bba2ff",
    description:
      "Fill fights with summons, clones, turrets, plants, and companions. Use them for vision, blocking skillshots, and controlling entrances.",
    sample: {
      top: "Yorick",
      jungle: "Ivern",
      mid: "Annie",
      bot: "Heimerdinger",
      support: "Zyra",
    },
    champions: pool(
      "Annie",
      "Elise",
      "Heimerdinger",
      "Ivern",
      "Maokai",
      "Malzahar",
      "Naafiri",
      "Shaco",
      "Yorick",
      "Zyra",
    ),
  },
  {
    id: "globals",
    title: "Everywhere at Once",
    type: "Shared mechanic",
    accent: "#70dfb2",
    description:
      "Global ultimates turn side-lane fights into team fights. Push lanes, call one target, stagger arrivals, and save a global for the escape.",
    sample: {
      top: "Shen",
      jungle: "Nocturne",
      mid: "TwistedFate",
      bot: "Ashe",
      support: "Senna",
    },
    champions: pool(
      "Ashe",
      "Briar",
      "Draven",
      "Ezreal",
      "Galio",
      "Gangplank",
      "Jinx",
      "Karthus",
      "Nocturne",
      "Pantheon",
      "Senna",
      "Shen",
      "Sion",
      "Soraka",
      "Taliyah",
      "TwistedFate",
      "Kled",
    ),
  },
  {
    id: "yordles",
    title: "Five Yordles",
    type: "Lore",
    accent: "#f1cf5b",
    description:
      "Yordles cover every role: protect Tristana, siege with Ziggs or Heimerdinger, or engage behind Poppy and Gnar.",
    sample: {
      top: "Gnar",
      jungle: "Poppy",
      mid: "Vex",
      bot: "Tristana",
      support: "Lulu",
    },
    champions: pool(
      "Corki",
      "Gnar",
      "Heimerdinger",
      "Kennen",
      "Kled",
      "Lulu",
      "Poppy",
      "Rumble",
      "Teemo",
      "Tristana",
      "Veigar",
      "Vex",
      "Ziggs",
    ),
  },
  {
    id: "knockups",
    title: "Knockup Relay",
    type: "Team combo",
    accent: "#82aaff",
    description:
      "Chain airborne effects for Yasuo and Samira. Set an engage order, then stagger knockups to interrupt escapes instead of overlapping.",
    sample: {
      top: "KSante",
      jungle: "MonkeyKing",
      mid: "Yasuo",
      bot: "Samira",
      support: "Alistar",
    },
    champions: pool(
      "Alistar",
      "Chogath",
      "Diana",
      "Gragas",
      "JarvanIV",
      "KSante",
      "Malphite",
      "Nautilus",
      "Ornn",
      "Rell",
      "Samira",
      "MonkeyKing",
      "Yasuo",
      "Yone",
      "Zac",
    ),
  },
  {
    id: "reset-city",
    title: "Reset City",
    type: "Shared mechanic",
    accent: "#ff4f70",
    description:
      "One takedown starts the chain. Focus the easiest target, then use each reset and burst of movement to roll through the remaining team.",
    sample: {
      top: "Darius",
      jungle: "Viego",
      mid: "Katarina",
      bot: "Jinx",
      support: "Pyke",
    },
    champions: pool(
      "Ahri",
      "Akshan",
      "Darius",
      "Belveth",
      "Viego",
      "Katarina",
      "Locke",
      "Khazix",
      "Tristana",
      "Jinx",
      "Samira",
      "Pyke",
      "Vex",
    ),
  },
  {
    id: "protect-president",
    title: "Protect the President",
    type: "Team combo",
    accent: "#72e6a1",
    description:
      "Build shields, healing, and peel around one hypercarry. Hold defensive cooldowns until enemies commit, then let the president clean up.",
    sample: {
      top: "Shen",
      jungle: "Ivern",
      mid: "Karma",
      bot: "KogMaw",
      support: "Braum",
    },
    champions: pool(
      "Shen",
      "Ivern",
      "Galio",
      "Karma",
      "Aphelios",
      "KogMaw",
      "Jinx",
      "Twitch",
      "Braum",
      "Janna",
      "Lulu",
      "Milio",
      "Renata",
      "Soraka",
      "TahmKench",
      "Taric",
      "Zilean",
    ),
  },
  {
    id: "wombo-combo",
    title: "The Wombo Combo",
    type: "Team combo",
    accent: "#ff8a3d",
    description:
      "Group the enemy team with one engage, then layer your area-of-effect ultimates. Stagger the crowd control so nobody escapes.",
    sample: {
      top: "Kennen",
      jungle: "Amumu",
      mid: "Orianna",
      bot: "MissFortune",
      support: "Rell",
    },
    champions: pool(
      "Kennen",
      "Gnar",
      "Malphite",
      "Rumble",
      "Amumu",
      "Diana",
      "JarvanIV",
      "MonkeyKing",
      "Neeko",
      "Orianna",
      "MissFortune",
      "Samira",
      "Rell",
      "Seraphine",
    ),
  },
  {
    id: "against-the-wall",
    title: "Against the Wall",
    type: "Team combo",
    accent: "#d5a253",
    description:
      "Create and weaponize terrain. Box enemies in with walls and pillars, then pin them against the nearest surface before they can escape.",
    sample: {
      top: "Poppy",
      jungle: "Taliyah",
      mid: "Qiyana",
      bot: "Vayne",
      support: "Bard",
    },
    champions: pool(
      "Anivia",
      "Bard",
      "Gnar",
      "JarvanIV",
      "Poppy",
      "Qiyana",
      "Taliyah",
      "Trundle",
      "Vayne",
      "Veigar",
    ),
  },
  {
    id: "infinite-scaling",
    title: "Infinite Scaling",
    type: "Shared mechanic",
    accent: "#b58cff",
    description:
      "Every role gains permanent power. Farm stacks, avoid rushed fights, and force opponents to end before the numbers take over.",
    sample: {
      top: "Sion",
      jungle: "Shyvana",
      mid: "Veigar",
      bot: "Smolder",
      support: "Senna",
    },
    champions: pool(
      "AurelionSol",
      "Bard",
      "Belveth",
      "Chogath",
      "Sion",
      "Nasus",
      "Shyvana",
      "Kindred",
      "Veigar",
      "Swain",
      "Smolder",
      "Senna",
      "Thresh",
    ),
  },
  {
    id: "not-dead-yet",
    title: "Not Dead Yet",
    type: "Shared mechanic",
    accent: "#6fe0df",
    description:
      "Revives and death-denial ultimates make takedowns uncertain. Bait key cooldowns, survive the burst, and return to finish the fight.",
    sample: {
      top: "Zac",
      jungle: "Kindred",
      mid: "Anivia",
      bot: "Akshan",
      support: "Zilean",
    },
    champions: pool(
      "Zac",
      "Tryndamere",
      "Sion",
      "Kindred",
      "Karthus",
      "Anivia",
      "Akshan",
      "Ekko",
      "Kayle",
      "KogMaw",
      "Renata",
      "Taric",
      "Zilean",
    ),
  },
  {
    id: "demacia",
    title: "DEMACIAAA",
    type: "Lore",
    accent: "#f2cf67",
    description:
      "Demacia fields disciplined frontliners and powerful protection. Lead with Jarvan or Galio, then rally around a ranged carry.",
    sample: {
      top: "Garen",
      jungle: "JarvanIV",
      mid: "Lux",
      bot: "Vayne",
      support: "Sona",
    },
    champions: pool(
      "Fiora",
      "Garen",
      "Poppy",
      "JarvanIV",
      "Shyvana",
      "XinZhao",
      "Galio",
      "Lux",
      "Sylas",
      "Lucian",
      "Quinn",
      "Vayne",
      "Sona",
    ),
  },
  {
    id: "ionia",
    title: "All Ionia",
    type: "Lore",
    accent: "#e79ad9",
    description:
      "Ionia blends mobility, precision, and explosive counter-engage. Draw enemies into a bad fight, then collapse from several angles.",
    sample: {
      top: "Shen",
      jungle: "LeeSin",
      mid: "Ahri",
      bot: "Xayah",
      support: "Rakan",
    },
    champions: pool(
      "Irelia",
      "Kennen",
      "Shen",
      "LeeSin",
      "MonkeyKing",
      "Ahri",
      "Akali",
      "Yasuo",
      "Yone",
      "Zed",
      "Jhin",
      "Xayah",
      "Karma",
      "Rakan",
    ),
  },
  {
    id: "zaun",
    title: "All Zaun",
    type: "Lore",
    accent: "#78d45b",
    description:
      "Zaun thrives on reckless invention, chemical durability, and chaotic skirmishes. Chase extended fights while Jinx or Zeri fires from behind.",
    sample: {
      top: "Singed",
      jungle: "Warwick",
      mid: "Viktor",
      bot: "Jinx",
      support: "Renata",
    },
    champions: pool(
      "Singed",
      "Urgot",
      "Ekko",
      "Warwick",
      "Zac",
      "Viktor",
      "Jinx",
      "Twitch",
      "Zeri",
      "Blitzcrank",
      "Janna",
      "Renata",
    ),
  },
  {
    id: "shadow-isles",
    title: "All Shadow Isles",
    type: "Lore",
    accent: "#55d6b3",
    description:
      "The Black Mist brings engage and champions who refuse to stay buried. Force long fights, collect resets, and drag survivors into the dark.",
    sample: {
      top: "Gwen",
      jungle: "Viego",
      mid: "Karthus",
      bot: "Kalista",
      support: "Thresh",
    },
    champions: pool(
      "Gwen",
      "Yorick",
      "Elise",
      "Hecarim",
      "Maokai",
      "Viego",
      "Karthus",
      "Vex",
      "Kalista",
      "Thresh",
    ),
  },
  {
    id: "bilgewater",
    title: "All Bilgewater",
    type: "Lore",
    accent: "#4eb6c2",
    description:
      "Bilgewater fights dirty with barrels, ambushes, and hard picks. Isolate one target and cash in before the enemy regroups.",
    sample: {
      top: "Gangplank",
      jungle: "Graves",
      mid: "TwistedFate",
      bot: "MissFortune",
      support: "Pyke",
    },
    champions: pool(
      "Gangplank",
      "Illaoi",
      "Graves",
      "Fizz",
      "TwistedFate",
      "MissFortune",
      "Nautilus",
      "Pyke",
      "TahmKench",
    ),
  },
  {
    id: "shurima",
    title: "All Shurima",
    type: "Lore",
    accent: "#e8b84f",
    description:
      "Shurima combines an imposing frontline with long-range control and late-game carries. Hold enemies in place while Azir, Sivir, or Xerath dominates.",
    sample: {
      top: "KSante",
      jungle: "Rammus",
      mid: "Azir",
      bot: "Sivir",
      support: "Xerath",
    },
    champions: pool(
      "KSante",
      "Nasus",
      "Renekton",
      "Rammus",
      "Taliyah",
      "Akshan",
      "Azir",
      "Sivir",
      "Xerath",
    ),
  },
  {
    id: "noxus",
    title: "All Noxus",
    type: "Lore",
    accent: "#c94b52",
    description:
      "Noxus rewards aggression and strength in extended fights. Break the frontline, secure one takedown, and keep advancing.",
    sample: {
      top: "Darius",
      jungle: "Briar",
      mid: "Katarina",
      bot: "Samira",
      support: "Swain",
    },
    champions: pool(
      "Ambessa",
      "Darius",
      "Kled",
      "Riven",
      "Sion",
      "Briar",
      "Talon",
      "Katarina",
      "Leblanc",
      "Swain",
      "Draven",
      "Samira",
      "Rell",
    ),
  },
  {
    id: "targon",
    title: "All Targon",
    type: "Lore",
    accent: "#9d8cff",
    description:
      "Targon's Aspects wield powerful team-fight ultimates. Survive the opening clash, then answer with overwhelming cosmic force.",
    sample: {
      top: "Pantheon",
      jungle: "Diana",
      mid: "Zoe",
      bot: "Aphelios",
      support: "Leona",
    },
    champions: pool(
      "Pantheon",
      "Diana",
      "AurelionSol",
      "Zoe",
      "Aphelios",
      "Leona",
      "Soraka",
      "Taric",
    ),
  },
  {
    id: "void",
    title: "All Void",
    type: "Lore",
    accent: "#a765e8",
    description:
      "The Void brings scaling threats, suppression, and relentless pursuit. Isolate prey, consume objectives, and adapt.",
    sample: {
      top: "Chogath",
      jungle: "Belveth",
      mid: "Malzahar",
      bot: "Kaisa",
      support: "Velkoz",
    },
    champions: pool(
      "Chogath",
      "Belveth",
      "RekSai",
      "Kassadin",
      "Malzahar",
      "Kaisa",
      "KogMaw",
      "Velkoz",
    ),
  },
  {
    id: "ixtal",
    title: "All Ixtal",
    type: "Lore",
    accent: "#55c786",
    description:
      "Ixtal controls the jungle through elemental magic and sudden ambushes. Fight around terrain and strike before enemies form up.",
    sample: {
      top: "Malphite",
      jungle: "Rengar",
      mid: "Qiyana",
      bot: "Neeko",
      support: "Milio",
    },
    champions: pool(
      "Malphite",
      "Rengar",
      "Nidalee",
      "Qiyana",
      "Neeko",
      "Milio",
      "Zyra",
    ),
  },
];

export const botCombos = [
  {
    champions: ["Veigar", "Poppy"],
    title: "Veigar + Poppy",
    text: "Knock enemies into the edge of Event Horizon.",
  },
  {
    champions: ["Rengar", "Ivern"],
    title: "Rengar + Ivern",
    text: "Grow extra bushes so Rengar always has a leap ready.",
  },
  {
    champions: ["Yasuo", "Nautilus"],
    title: "Yasuo + Nautilus",
    text: "Turn every Nautilus engage into an airborne delivery.",
  },
  {
    champions: ["Lux", "Morgana"],
    title: "Lux + Morgana",
    text: "Chain long-range bindings and punish anyone caught by either.",
  },
  {
    champions: ["Nilah", "Taric"],
    title: "Nilah + Taric",
    text: "Share healing, crowd control, and a very committed all-in.",
  },
  {
    champions: ["Kalista", "Neeko"],
    title: "Kalista + Neeko",
    text: "Throw a channeling Neeko directly into the fight.",
  },
  {
    champions: ["MissFortune", "Zoe"],
    title: "Miss Fortune + Zoe",
    text: "Land Sleepy Trouble Bubble, then line up Bullet Time.",
  },
  {
    champions: ["Yorick", "Zilean"],
    title: "Yorick + Zilean",
    text: "Attach Zilean's bombs to Yorick's summons and send them forward.",
  },
];
